name: Deploy Function Apps to Azure

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: false
        description: Artifact name
        default: 'app'
      github_branch_name:
        type: string
        required: false
        description: GitHub branch name
        default: 'main'

env:
  AZURE_RESOURCE_GROUP_NAME: 'rg-${{ secrets.AZURE_ENV_NAME }}'
  AZURE_APIM_NAME: 'apim-${{ secrets.AZURE_ENV_NAME }}'

jobs:
  deploy_azure:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [ { "name": "apikeyauth", "suffix": "api-key-auth", "path": "ApiKeyAuth", "nv": "API_KEY_AUTH" } ]

    env:
      AZURE_FNCAPP_NAME: 'fncapp-${{ secrets.AZURE_ENV_NAME }}-${{ matrix.app.suffix }}'

    steps:
    - name: Download Function app artifact
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/published

    - name: Zip Function app artifact
      shell: pwsh
      run: |
        $destination_path = "published/fncapp.zip"

        Compress-Archive -Path published/${{ inputs.artifact_name }}-${{ matrix.app.name }}/* -DestinationPath $destination_path

        echo "AZURE_FNCAPP_PATH=$destination_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Sign in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy FunctionApp artifact to Azure
      shell: bash
      run: |
        az functionapp deploy \
          -g ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          -n ${{ env.AZURE_FNCAPP_NAME }} \
          --src-path ${{ env.AZURE_FNCAPP_PATH }} \
          --type zip \
          --verbose

    - name: Update function key on APIM
      shell: bash
      run: |
        fncapp_key=$(az functionapp keys list \
          -g ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          -n ${{ env.AZURE_FNCAPP_NAME }} \
          --query "functionKeys.default" -o tsv)

        apim_nv=$(az apim nv update \
          -g ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          -n ${{ env.AZURE_APIM_NAME }} \
          --named-value-id X_FUNCTIONS_KEY_${{ matrix.app.nv }} \
          --value $fncapp_key)
