name: 'On Called for Deploying Static Web Apps to Azure'

on:
  workflow_call:
    inputs:
      matrix_json:
        type: string
        required: true
        description: Matrix JSON array
      artifact_name:
        type: string
        required: false
        description: Artifact name
        default: 'app'

env:
  AZURE_RESOURCE_GROUP_NAME: 'rg-${{ secrets.AZURE_ENV_NAME }}'
  AZURE_APIM_NAME: 'apim-${{ secrets.AZURE_ENV_NAME }}'

jobs:
  deploy_azure:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ${{ fromJson(inputs.matrix_json) }}

    env:
      AZURE_STTAPP_NAME: 'sttapp-${{ secrets.AZURE_ENV_NAME }}'

    steps:
    - name: Download Static app artifact
      if: matrix.app.name == 'webapp'
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/published

    - name: Sign in to Azure
      if: matrix.app.name == 'webapp'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get SWA token
      if: matrix.app.name == 'webapp'
      shell: bash
      run: |
        swa_token=$(az staticwebapp secrets list -g $AZURE_RESOURCE_GROUP_NAME -n $AZURE_STTAPP_NAME --query "properties.apiKey" -o tsv)

        echo "::add-mask::$swa_token"
        echo "SWA_TOKEN=$swa_token" >> $GITHUB_ENV

    - name: Deploy SWA to Azure
      if: matrix.app.name == 'webapp'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        skip_app_build: true
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "${{ github.workspace }}/published/${{ inputs.artifact_name }}-web/wwwroot" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
