name: 'On Called for Doing Build & Test & Upload'

on:
  workflow_call:
    inputs:
      matrix_json:
        type: string
        required: true
        description: Matrix JSON array
      artifact_name:
        type: string
        required: false
        description: Artifact name
        default: 'app'
      is_pullrequest:
        type: string
        required: false
        description: Value indicating whether the caller event is pull request or not
        default: 'false'

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ${{ fromJson(inputs.matrix_json) }}

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore .

    - name: Build solution
      shell: bash
      run: |
        dotnet build . -c Release

    - name: Test solution
      shell: bash
      run: |
        dotnet test . -c Release

    - name: Create artifacts - WebApp
      if: inputs.is_pullrequest == 'false' && matrix.app.name == 'webapp'
      shell: pwsh
      run: |
        pushd src/WebApp/wwwroot

        Rename-Item -Path ./appsettings.sample.json -NewName appsettings.json

        $(Get-Content -Path ./appsettings.json -Raw) -replace "{{AZURE_ENV_NAME}}", "${{ secrets.AZURE_ENV_NAME }}" | `
                  ConvertFrom-Json | ConvertTo-Json -Depth 10 | `
                  Out-File -Path ./appsettings.json -Force

        popd

        dotnet publish -c Release

    - name: Create artifacts - FunctionApp
      if: inputs.is_pullrequest == 'false' && matrix.app.name != 'webapp'
      shell: bash
      run: |
        dotnet publish -c Release

    - name: Add app paths to env - WebApp
      if: inputs.is_pullrequest == 'false' && matrix.app.name == 'webapp'
      shell: pwsh
      run: |
        $appPath = "src/${{ matrix.app.path }}/bin/Release/net7.0/publish"

        echo "APP_PATH=$appPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Add app paths to env - FunctionApp
      if: inputs.is_pullrequest == 'false' && matrix.app.name != 'webapp'
      shell: pwsh
      run: |
        $appPath = "src/${{ matrix.app.path }}/bin/Release/net6.0/publish"

        echo "APP_PATH=$appPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Upload app artifact
      if: inputs.is_pullrequest == 'false'
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.artifact_name }}-${{ matrix.app.name }}"
        path: "${{ github.workspace }}/${{ env.APP_PATH }}"
        retention-days: 3
